project_id = "lbfabewnshfjdjfosqxl"

[functions.proxmox-api]
verify_jwt = false

[functions.list-vms]
verify_jwt = false

[functions.vm-console]
verify_jwt = false

[functions.vm-actions]
verify_jwt = false

[functions.vnc-relay]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[edge_runtime]
policy = "per_worker"
